name: CI-Developer-Education

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  push:
    branches:
      - main
      - litium-7
      - litium-8
    paths:
    - 'Developer Education/Presentation/**'
    - '.github/workflows/developer-education.yml'
    
#  pull_request:
#    branches: 
#      - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: '${{ secrets.AZURE_DEVOPS_URL }}/Litium.Studio'
            azure-pipeline-name: 'Container.LitiumDevSlides CI'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_BUILD_TOKEN }}
            azure-pipeline-variables:  '{"branch": "${GITHUB_REF##*/}"}'
